### ISSUE TITLE
Problem accessing URL: code 403

### ISSUE THREAD

**Issue by itsabubakarshf** [fly-metothemoon/GWsearch#2]
Command: python gowild_scraper.py -o AUS -d 1
On testing the bot I got error: Problem accessing URL: code 403

@fly-metothemoon will you please explain why we can't access the below data? We are getting 403 because of Captcha appearance on Frontier Airlines?

           print(f"flight {go_wild_count}. {flight['stopsText']}")
            print(f"\tDate: {info['departureDate'][5:10]}")
            print(f"\tDepart: {info['departureDateFormatted']}")
            print(f"\tTotal flight time: {flight['duration']}")
            print(f"Price: ${flight['goWildFare']}")
![Screenshot from 2023-07-07 14-47-28](https://github.com/fly-metothemoon/GWsearch/assets/45329784/2d5d740c-01b0-4655-87c0-48528da18fed)

**Comment by aps2002** [comment]
Getting a similar error when running `python gowild_scraper.py -o ATL -d 2`

**Comment by itsabubakarshf** [comment]
I found the reason yesterday, it's because of captcha :)
We can use proxies and what more? 

@fly-metothemoon

**Comment by itsabubakarshf** [comment]
Done :)

**Comment by atiqsamtia** [comment]
@itsabubakarshf were you able to get the response of all flights? For me 4 requests were successful and after that 403 messages. I increased the sleep time too. Which proxies worked for you?

![image](https://github.com/fly-metothemoon/GWsearch/assets/5112753/c0225aaf-a856-4288-9994-625c86742e6b)
